language: "node_js"
node_js:
  - "0.10"
before_install: sudo apt-get update
install:
  - sudo apt-get install graphicsmagick fontconfig libfreetype6-dev
  - npm install
after_success :
  - npm run coveralls
